int _putchar(char);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int add (int, int);
void times_table(void);
int print_sign(int n);
int _isalpha(int c);
int _abs(int);
void print_times_table(int n);
